version: '3.1'

services:
  postgres:
    build: ./db
    env_file:
      - config.env
    volumes:
    - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U pguser -d blog_db" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    container_name: pg_database
  web:
    build: .
    env_file:
      - config.env
    ports:
      - "5000:5000"
    volumes:
      - .:/code
    depends_on:
      - postgres
    container_name: flask_app
volumes:
  postgres_data:
